
const ERC20_ABI=["function name() view returns (string)","function symbol() view returns (string)","function decimals() view returns (uint8)","function balanceOf(address owner) view returns (uint256)","function transfer(address to,uint256 amount) returns (bool)","function allowance(address owner,address spender) view returns (uint256)","function approve(address spender,uint256 amount) returns (bool)"];
const V2_ROUTER_ABI=["function WETH() view returns (address)","function getAmountsOut(uint amountIn,address[] calldata path) view returns (uint[] memory amounts)","function swapExactETHForTokensSupportingFeeOnTransferTokens(uint amountOutMin,address[] calldata path,address to,uint deadline) payable","function swapExactTokensForETHSupportingFeeOnTransferTokens(uint amountIn,uint amountOutMin,address[] calldata path,address to,uint deadline)"];
const state={provider:null,wallet:null,rpcUrl:null,chainId:null,token:null,tokenMeta:null,plan:[],running:false,stopped:false,generatedWallets:[],tradeProvider:null,tradeRouter:null,tradeTokenMeta:null,tradePlan:[],tradeStopped:false,collectProvider:null,collectTokenMeta:null,collectPlan:[],collectStopped:false};
const $=id=>document.getElementById(id);
const els={pageTitle:$("pageTitle"),breadcrumbText:$("breadcrumbText"),networkStatus:$("networkStatus"),transferPage:$("transferPage"),walletPage:$("walletPage"),tradePage:$("tradePage"),collectPage:$("collectPage"),rpcUrl:$("rpcUrl"),privateKey:$("privateKey"),tokenAddress:$("tokenAddress"),transferNativeAsset:$("transferNativeAsset"),minAmount:$("minAmount"),maxAmount:$("maxAmount"),fixedAmount:$("fixedAmount"),delaySeconds:$("delaySeconds"),randomDecimals:$("randomDecimals"),recipients:$("recipients"),walletInfo:$("walletInfo"),tokenInfo:$("tokenInfo"),summaryText:$("summaryText"),planBody:$("planBody"),metricWallet:$("metricWallet"),metricToken:$("metricToken"),metricCount:$("metricCount"),metricStatus:$("metricStatus"),randomAmountPanel:$("randomAmountPanel"),fixedAmountPanel:$("fixedAmountPanel"),randomModeTab:$("randomModeTab"),fixedModeTab:$("fixedModeTab"),walletGenerateCount:$("walletGenerateCount"),generatedWalletBody:$("generatedWalletBody"),walletGenerateStatus:$("walletGenerateStatus"),walletGenerateTotal:$("walletGenerateTotal"),tradeModeMetric:$("tradeModeMetric"),tradeWalletCountMetric:$("tradeWalletCountMetric"),tradeStatusMetric:$("tradeStatusMetric"),tradeRpcUrl:$("tradeRpcUrl"),tradeRouterAddress:$("tradeRouterAddress"),tradeTokenAddress:$("tradeTokenAddress"),tradeTokenInfo:$("tradeTokenInfo"),buyTradeTab:$("buyTradeTab"),sellTradeTab:$("sellTradeTab"),buyAmountPanel:$("buyAmountPanel"),sellAmountPanel:$("sellAmountPanel"),tradeBuyNativeAmount:$("tradeBuyNativeAmount"),tradeSellTokenAmount:$("tradeSellTokenAmount"),tradeSellAllPercent:$("tradeSellAllPercent"),tradeSlippage:$("tradeSlippage"),tradeDelaySeconds:$("tradeDelaySeconds"),tradeDeadlineMinutes:$("tradeDeadlineMinutes"),tradeConcurrency:$("tradeConcurrency"),tradePrivateKeys:$("tradePrivateKeys"),tradeSummaryText:$("tradeSummaryText"),tradePlanBody:$("tradePlanBody"),collectTokenMetric:$("collectTokenMetric"),collectWalletCountMetric:$("collectWalletCountMetric"),collectReadyCountMetric:$("collectReadyCountMetric"),collectStatusMetric:$("collectStatusMetric"),collectRpcUrl:$("collectRpcUrl"),collectTokenAddress:$("collectTokenAddress"),collectNativeAsset:$("collectNativeAsset"),collectToAddress:$("collectToAddress"),collectDelaySeconds:$("collectDelaySeconds"),collectConcurrency:$("collectConcurrency"),collectPrivateKeys:$("collectPrivateKeys"),collectTokenInfo:$("collectTokenInfo"),collectRuleText:$("collectRuleText"),collectRuleWarning:$("collectRuleWarning"),collectSafetyWarning:$("collectSafetyWarning"),collectSummaryText:$("collectSummaryText"),collectPlanBody:$("collectPlanBody")};
function ensureEthers(){if(!window.ethers)throw new Error("ethers.js 没有加载成功。请确认网络可以访问 CDN。");}
function setMetric(el,v){if(el)el.textContent=v}
function shortAddress(a){return a?`${a.slice(0,6)}...${a.slice(-4)}`:"-"}
function toastError(e){alert(e?.message||String(e))}
function normalizePrivateKey(v){const pk=String(v||"").trim();if(!pk)throw new Error("请输入私钥");const n=pk.startsWith("0x")?pk:`0x${pk}`;if(!/^0x[0-9a-fA-F]{64}$/.test(n))throw new Error("私钥格式不正确");return n}
function switchPage(page){document.querySelectorAll(".menu-item").forEach(i=>i.classList.toggle("active",i.dataset.page===page));els.transferPage.classList.toggle("active",page==="transfer");els.walletPage.classList.toggle("active",page==="wallet");els.tradePage.classList.toggle("active",page==="trade");els.collectPage.classList.toggle("active",page==="collect");if(page==="wallet"){els.pageTitle.textContent="EVM 钱包生成";els.breadcrumbText.textContent="工具 / EVM / 钱包生成";els.networkStatus.textContent="本地生成"}else if(page==="trade"){els.pageTitle.textContent="EVM 一键买卖";els.breadcrumbText.textContent="工具 / EVM / 一键买卖";els.networkStatus.textContent="交易工作区"}else if(page==="collect"){els.pageTitle.textContent="EVM 一键归集";els.breadcrumbText.textContent="工具 / EVM / 一键归集";els.networkStatus.textContent="归集工作区"}else{els.pageTitle.textContent="EVM 批量转账";els.breadcrumbText.textContent="工具 / EVM / 批量转账";els.networkStatus.textContent=state.wallet?els.networkStatus.textContent:"未连接"}}
function getTransferAssetType(){return els.transferNativeAsset.checked?"native":"token"}
function getTransferMode(){return document.querySelector('input[name="transferMode"]:checked')?.value||"random"}
function getNativeSymbol(chainId){const id=Number(chainId||0);if(id===56||id===97)return"BNB";if([1,5,11155111,17000,10,11155420,42161,421614,8453,84532,59144,59141,534352,534351,81457,168587773,324,300].includes(id))return"ETH";return"原生币"}
function resetTransferPlan(status){if(state.plan.length){state.plan=[];renderPlan();$("executeBtn").disabled=true;if(status)setMetric(els.metricStatus,status)}}
function refreshTransferAssetType(){const n=getTransferAssetType()==="native";els.tokenAddress.disabled=n;$("loadTokenBtn").textContent=n?"读取主币信息":"读取 Token 信息";els.tokenInfo.innerHTML=n?`<div class="muted">主币通过当前 RPC 读取发送钱包余额，不需要合约地址。</div>`:`<div class="muted">读取后显示资产名称、符号、精度、发送钱包余额。</div>`;setMetric(els.metricToken,n?"主币":"未读取");resetTransferPlan("资产类型已变更")}
function refreshTransferMode(){const r=getTransferMode()==="random";els.randomAmountPanel.classList.toggle("hidden",!r);els.fixedAmountPanel.classList.toggle("hidden",r);els.randomDecimals.disabled=!r;els.randomModeTab.classList.toggle("active",r);els.fixedModeTab.classList.toggle("active",!r);resetTransferPlan("规则已变更")}
function getProvider(){ensureEthers();const rpc=els.rpcUrl.value.trim();if(!rpc)throw new Error("请输入 RPC URL");return new ethers.JsonRpcProvider(rpc)}
async function initWallet(){ensureEthers();const rpc=els.rpcUrl.value.trim(),provider=getProvider(),wallet=new ethers.Wallet(normalizePrivateKey(els.privateKey.value),provider);const net=await provider.getNetwork();const bal=await provider.getBalance(wallet.address),symbol=getNativeSymbol(net.chainId);state.provider=provider;state.wallet=wallet;state.rpcUrl=rpc;state.chainId=net.chainId;els.networkStatus.textContent=`已连接 Chain ID: ${net.chainId}`;setMetric(els.metricWallet,shortAddress(wallet.address));setMetric(els.metricStatus,"钱包已验证");els.walletInfo.innerHTML=`<div><strong>发送地址：</strong>${wallet.address}</div><div><strong>Chain ID：</strong>${net.chainId}</div><div><strong>原生币余额：</strong>${ethers.formatEther(bal)} ${symbol}</div>`}
async function ensureTransferWallet(){const pk=normalizePrivateKey(els.privateKey.value),rpc=els.rpcUrl.value.trim();if(!state.wallet||state.rpcUrl!==rpc||state.wallet.privateKey.toLowerCase()!==pk.toLowerCase())await initWallet()}
async function loadToken(){ensureEthers();await ensureTransferWallet();const addr=els.tokenAddress.value.trim();if(!ethers.isAddress(addr))throw new Error("Token 合约地址不正确");const token=new ethers.Contract(addr,ERC20_ABI,state.wallet);const [name,symbol,decimals,rawBalance]=await Promise.all([token.name().catch(()=>""),token.symbol().catch(()=>""),token.decimals(),token.balanceOf(state.wallet.address)]);state.token=token;state.tokenMeta={type:"token",address:ethers.getAddress(addr),name,symbol,decimals:Number(decimals),rawBalance};setMetric(els.metricToken,symbol||shortAddress(addr));setMetric(els.metricStatus,"Token 已读取");els.tokenInfo.innerHTML=`<div><strong>Token：</strong>${name||"-"} ${symbol?`(${symbol})`:""}</div><div><strong>精度：</strong>${decimals}</div><div><strong>余额：</strong>${ethers.formatUnits(rawBalance,decimals)} ${symbol||""}</div>`}
async function loadNativeAsset(){ensureEthers();await ensureTransferWallet();const rawBalance=await state.provider.getBalance(state.wallet.address),symbol=getNativeSymbol(state.chainId);state.token=null;state.tokenMeta={type:"native",address:null,name:"原生币",symbol,decimals:18,rawBalance};setMetric(els.metricToken,symbol);setMetric(els.metricStatus,"原生币已读取");els.tokenInfo.innerHTML=`<div><strong>资产：</strong>原生币 (${symbol})</div><div><strong>精度：</strong>18</div><div><strong>余额：</strong>${ethers.formatEther(rawBalance)} ${symbol}</div>`}
async function loadTransferAsset(){return getTransferAssetType()==="native"?loadNativeAsset():loadToken()}
function parseRecipients(){ensureEthers();const seen=new Set(),arr=[];els.recipients.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).forEach(line=>{const a=line.split(/[,\s]+/)[0];if(!ethers.isAddress(a))throw new Error(`接收地址格式错误：${line}`);const c=ethers.getAddress(a);if(!seen.has(c.toLowerCase())){seen.add(c.toLowerCase());arr.push(c)}});if(!arr.length)throw new Error("请输入至少一个接收地址");return arr}
function randomAmount(min,max,d){const scale=10**d;const lo=Math.ceil(min*scale),hi=Math.floor(max*scale);if(!Number.isSafeInteger(lo)||!Number.isSafeInteger(hi))throw new Error("随机范围过大或小数位过多");const v=lo+Math.floor(Math.random()*(hi-lo+1));return d===0?String(v):(v/scale).toFixed(d).replace(/\.?0+$/,"")}
function assertAmount(v,name){const t=String(v||"").trim();if(!t)throw new Error(`请输入${name}`);const n=Number(t);if(!Number.isFinite(n)||n<=0)throw new Error(`${name}必须大于 0`);return t}
async function getNativeTransferGasReserve(count){const fee=await state.provider.getFeeData().catch(()=>({})),gasPrice=fee.maxFeePerGas||fee.gasPrice||0n;return gasPrice*21000n*BigInt(count)}
async function buildPlan(){ensureEthers();await loadTransferAsset();const meta=state.tokenMeta,rec=parseRecipients(),mode=getTransferMode();let plan=[];if(mode==="fixed"){const t=assertAmount(els.fixedAmount.value,"固定转账数量");const wei=ethers.parseUnits(t,meta.decimals);plan=rec.map((to,i)=>({index:i+1,to,amountText:t,amountWei:wei,status:"待执行",hashOrError:""}))}else{const min=Number(els.minAmount.value),max=Number(els.maxAmount.value),d=Number(els.randomDecimals.value);if(!Number.isFinite(min)||!Number.isFinite(max)||min<=0||max<=0)throw new Error("随机区间必须大于 0");if(min>max)throw new Error("随机区间最小值不能大于最大值");if(!Number.isInteger(d)||d<0||d>meta.decimals)throw new Error(`随机小数位必须在 0 到 ${meta.decimals} 之间`);plan=rec.map((to,i)=>{const t=randomAmount(min,max,d);return{index:i+1,to,amountText:t,amountWei:ethers.parseUnits(t,meta.decimals),status:"待执行",hashOrError:""}})}const total=plan.reduce((s,x)=>s+x.amountWei,0n);if(meta.type==="native"){const gasReserve=await getNativeTransferGasReserve(plan.length);if(total+gasReserve>meta.rawBalance)throw new Error(`原生币余额不足，需预留约 ${ethers.formatEther(gasReserve)} ${meta.symbol} 作为 gas`)}else if(total>meta.rawBalance)throw new Error("Token 余额不足");state.plan=plan;setMetric(els.metricCount,String(plan.length));setMetric(els.metricStatus,"预览已生成");renderPlan();$("executeBtn").disabled=false}
function renderStatus(s){if(s==="成功")return`<span class="badge ok">成功</span>`;if(s==="失败")return`<span class="badge err">失败</span>`;return`<span class="badge">${s}</span>`}
function renderPlan(){if(!state.plan.length){els.planBody.innerHTML=`<tr><td colspan="5" class="empty">请先生成转账预览</td></tr>`;els.summaryText.textContent="暂无计划";setMetric(els.metricCount,"0");return}const total=state.plan.reduce((s,x)=>s+x.amountWei,0n);els.summaryText.textContent=`共 ${state.plan.length} 笔，合计 ${ethers.formatUnits(total,state.tokenMeta.decimals)} ${state.tokenMeta.symbol||""}`;els.planBody.innerHTML=state.plan.map(x=>`<tr><td>${x.index}</td><td class="hash">${x.to}</td><td>${x.amountText} ${state.tokenMeta.symbol||""}</td><td>${renderStatus(x.status)}</td><td class="hash">${x.hashOrError||"-"}</td></tr>`).join("")}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function executePlan(){ensureEthers();if(!state.plan.length)throw new Error("请先生成转账预览");const meta=state.tokenMeta,assetLabel=meta.type==="native"?meta.symbol:"Token";if(!confirm(`确认执行 ${state.plan.length} 笔 ${assetLabel} 转账？`))return;$("executeBtn").disabled=true;$("stopBtn").disabled=false;state.stopped=false;setMetric(els.metricStatus,"执行中");for(const item of state.plan){if(state.stopped){item.status="已停止";item.hashOrError="用户停止执行";renderPlan();continue}item.status="执行中";renderPlan();try{const tx=meta.type==="native"?await state.wallet.sendTransaction({to:item.to,value:item.amountWei}):await state.token.transfer(item.to,item.amountWei);item.hashOrError=tx.hash;renderPlan();const rc=await tx.wait();item.status=rc.status===1?"成功":"失败"}catch(e){item.status="失败";item.hashOrError=e?.shortMessage||e?.message||String(e)}renderPlan();await sleep(Math.round(Math.max(0,Number(els.delaySeconds.value||0))*1000))}$("stopBtn").disabled=true;setMetric(els.metricStatus,state.stopped?"已停止":"执行完成")}
function renderGeneratedWallets(){if(!state.generatedWallets.length){els.generatedWalletBody.innerHTML=`<tr><td colspan="3" class="empty">暂无生成的钱包</td></tr>`;$("copyWalletAddressBtn").disabled=true;$("copyWalletFullBtn").disabled=true;$("clearWalletGeneratedBtn").disabled=true;setMetric(els.walletGenerateStatus,"待生成");setMetric(els.walletGenerateTotal,"0");return}els.generatedWalletBody.innerHTML=state.generatedWallets.map(x=>`<tr><td>${x.index}</td><td class="hash">${x.address}</td><td class="hash">${x.privateKey}</td></tr>`).join("");$("copyWalletAddressBtn").disabled=false;$("copyWalletFullBtn").disabled=false;$("clearWalletGeneratedBtn").disabled=false;setMetric(els.walletGenerateStatus,"已生成");setMetric(els.walletGenerateTotal,String(state.generatedWallets.length))}
function generateWallets(){ensureEthers();const c=Number(els.walletGenerateCount.value);if(!Number.isInteger(c)||c<1||c>200)throw new Error("生成数量必须在 1 到 200 之间");if(!confirm(`确认生成 ${c} 个新钱包？`))return;state.generatedWallets=Array.from({length:c},(_,i)=>{const w=ethers.Wallet.createRandom();return{index:i+1,address:w.address,privateKey:w.privateKey}});renderGeneratedWallets()}
async function copyText(t){const ta=document.createElement("textarea");ta.value=t;document.body.appendChild(ta);ta.select();document.execCommand("copy");document.body.removeChild(ta)}
function getTradeMode(){return document.querySelector('input[name="tradeMode"]:checked')?.value||"buy"}
function refreshSellAllMode(){const all=els.tradeSellAllPercent.checked;els.tradeSellTokenAmount.disabled=all;els.tradeSellTokenAmount.placeholder=all?"已选择卖出 100%，自动读取钱包余额":"每个钱包固定卖出数量，例如：1000"}
function refreshTradeMode(){const buy=getTradeMode()==="buy";els.buyAmountPanel.classList.toggle("hidden",!buy);els.sellAmountPanel.classList.toggle("hidden",buy);els.buyTradeTab.classList.toggle("active",buy);els.sellTradeTab.classList.toggle("active",!buy);setMetric(els.tradeModeMetric,buy?"买入":"卖出");refreshSellAllMode();if(state.tradePlan.length){state.tradePlan=[];renderTradePlan();$("executeTradeBtn").disabled=true}}
function getTradeProvider(){ensureEthers();const rpc=els.tradeRpcUrl.value.trim();if(!rpc)throw new Error("请输入一键买卖 RPC URL");return new ethers.JsonRpcProvider(rpc)}
async function loadTradeTokenInfo(){ensureEthers();const provider=getTradeProvider();const routerAddr=els.tradeRouterAddress.value.trim(),tokenAddr=els.tradeTokenAddress.value.trim();if(!ethers.isAddress(routerAddr))throw new Error("Router 地址不正确");if(!ethers.isAddress(tokenAddr))throw new Error("Token 地址不正确");const router=new ethers.Contract(routerAddr,V2_ROUTER_ABI,provider),token=new ethers.Contract(tokenAddr,ERC20_ABI,provider);const [weth,name,symbol,decimals]=await Promise.all([router.WETH(),token.name().catch(()=>""),token.symbol().catch(()=>""),token.decimals()]);state.tradeProvider=provider;state.tradeRouter=router;state.tradeTokenMeta={routerAddress:ethers.getAddress(routerAddr),tokenAddress:ethers.getAddress(tokenAddr),weth:ethers.getAddress(weth),name,symbol,decimals:Number(decimals)};setMetric(els.tradeStatusMetric,"Token 已读取");els.tradeTokenInfo.innerHTML=`<div><strong>Token：</strong>${name||"-"} ${symbol?`(${symbol})`:""}</div><div><strong>精度：</strong>${decimals}</div><div><strong>Router：</strong>${ethers.getAddress(routerAddr)}</div><div><strong>WETH/WBNB：</strong>${ethers.getAddress(weth)}</div>`}
function parseTradePrivateKeys(){ensureEthers();const lines=els.tradePrivateKeys.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)throw new Error("请输入至少一个交易钱包私钥");const seen=new Set(),ws=[];for(const line of lines){const pk=normalizePrivateKey(line.split(/[,\s]+/)[0]);const w=new ethers.Wallet(pk);if(!seen.has(w.address.toLowerCase())){seen.add(w.address.toLowerCase());ws.push({index:ws.length+1,privateKey:pk,address:w.address})}}return ws}
function calcAmountOutMin(out,slip){const bps=BigInt(Math.floor(slip*100));if(bps<0n||bps>=10000n)throw new Error("滑点百分比必须小于 100");return out*(10000n-bps)/10000n}
function getTradeConcurrency(){const value=Number(els.tradeConcurrency.value);if(!Number.isInteger(value)||value<1||value>20)throw new Error("并发钱包数必须是 1 到 20 之间的整数");return value}
async function mapWithConcurrency(items,limit,mapper){const results=new Array(items.length);let next=0;async function worker(){while(next<items.length){const index=next++;results[index]=await mapper(items[index],index)}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return results}
async function buildTradePlan(){ensureEthers();if(!state.tradeTokenMeta)await loadTradeTokenInfo();const mode=getTradeMode(),wallets=parseTradePrivateKeys(),slip=Number(els.tradeSlippage.value),concurrency=getTradeConcurrency();if(!Number.isFinite(slip)||slip<0||slip>=100)throw new Error("滑点百分比必须在 0 到 100 之间");const meta=state.tradeTokenMeta,router=state.tradeRouter,provider=state.tradeProvider;let plan=[];if(mode==="buy"){const txt=assertAmount(els.tradeBuyNativeAmount.value,"买入金额"),amountIn=ethers.parseEther(txt),path=[meta.weth,meta.tokenAddress];let minOut=0n,quote="-";try{const a=await router.getAmountsOut(amountIn,path);minOut=calcAmountOutMin(a.at(-1),slip);quote=`预计最少获得 ${ethers.formatUnits(minOut,meta.decimals)} ${meta.symbol||"Token"}`}catch(e){quote="无法报价，执行时仍可能失败"}plan=wallets.map((w,i)=>({index:i+1,...w,mode,amountText:txt,amountIn,amountOutMin:minOut,unitLabel:"原生币",quoteText:quote,status:"待执行",hashOrError:""}))}else{const sellAll=els.tradeSellAllPercent.checked,token=new ethers.Contract(meta.tokenAddress,ERC20_ABI,provider),path=[meta.tokenAddress,meta.weth];let fixedTxt="",fixedIn=0n;if(!sellAll){fixedTxt=assertAmount(els.tradeSellTokenAmount.value,"卖出 Token 数量");fixedIn=ethers.parseUnits(fixedTxt,meta.decimals)}plan=await mapWithConcurrency(wallets,concurrency,async(w,i)=>{const amountIn=sellAll?await token.balanceOf(w.address):fixedIn,txt=sellAll?ethers.formatUnits(amountIn,meta.decimals):fixedTxt;if(amountIn<=0n)return{index:i+1,...w,mode,amountText:"0",amountIn,amountOutMin:0n,unitLabel:meta.symbol||"Token",quoteText:"Token 余额为 0，执行时跳过",status:"跳过",hashOrError:"Token 余额为 0"};let minOut=0n,quote="-";try{const a=await router.getAmountsOut(amountIn,path);minOut=calcAmountOutMin(a.at(-1),slip);quote=`${sellAll?"100% 卖出，":""}预计最少获得 ${ethers.formatEther(minOut)} 原生币`}catch(e){quote="无法报价，执行时仍可能失败"}return{index:i+1,...w,mode,amountText:txt,amountIn,amountOutMin:minOut,unitLabel:meta.symbol||"Token",quoteText:quote,status:"待执行",hashOrError:""}})}state.tradePlan=plan;setMetric(els.tradeWalletCountMetric,String(plan.length));setMetric(els.tradeStatusMetric,"预览已生成");renderTradePlan();$("executeTradeBtn").disabled=plan.every(x=>x.status==="跳过")}
function renderTradePlan(){if(!state.tradePlan.length){els.tradePlanBody.innerHTML=`<tr><td colspan="6" class="empty">请先生成买卖预览</td></tr>`;els.tradeSummaryText.textContent="暂无交易计划";setMetric(els.tradeWalletCountMetric,"0");return}els.tradeSummaryText.textContent=`${state.tradePlan[0].mode==="buy"?"买入":"卖出"}计划：共 ${state.tradePlan.length} 个钱包`;els.tradePlanBody.innerHTML=state.tradePlan.map(x=>`<tr><td>${x.index}</td><td class="hash">${x.address}</td><td>${x.mode==="buy"?"买入":"卖出"}</td><td><div>${x.amountText} ${x.unitLabel}</div><div class="muted">${x.quoteText}</div></td><td>${renderStatus(x.status)}</td><td class="hash">${x.hashOrError||"-"}</td></tr>`).join("")}
async function executeTradePlan(){ensureEthers();if(!state.tradePlan.length)throw new Error("请先生成买卖预览");const concurrency=getTradeConcurrency(),items=state.tradePlan.filter(x=>x.status!=="跳过"&&x.amountIn>0n);if(!items.length)throw new Error("没有可执行的交易钱包");if(!confirm(`确认以最多 ${concurrency} 个钱包并发执行 ${items.length} 笔一键买卖？`))return;state.tradeStopped=false;$("executeTradeBtn").disabled=true;$("stopTradeBtn").disabled=false;setMetric(els.tradeStatusMetric,`并发执行中 (${concurrency})`);const meta=state.tradeTokenMeta,provider=state.tradeProvider,delay=Math.round(Math.max(0,Number(els.tradeDelaySeconds.value||0))*1000),deadlineMin=Math.max(1,Number(els.tradeDeadlineMinutes.value||20)),pending=[];await mapWithConcurrency(items,concurrency,async item=>{if(state.tradeStopped){item.status="已停止";item.hashOrError="用户停止执行";renderTradePlan();return}item.status="执行中";item.hashOrError="";renderTradePlan();try{const wallet=new ethers.Wallet(item.privateKey,provider),router=new ethers.Contract(meta.routerAddress,V2_ROUTER_ABI,wallet);let tx;if(item.mode==="buy"){const deadline=Math.floor(Date.now()/1000)+deadlineMin*60;tx=await router.swapExactETHForTokensSupportingFeeOnTransferTokens(item.amountOutMin,[meta.weth,meta.tokenAddress],wallet.address,deadline,{value:item.amountIn})}else{const token=new ethers.Contract(meta.tokenAddress,ERC20_ABI,wallet),allowance=await token.allowance(wallet.address,meta.routerAddress);if(allowance<item.amountIn){const ap=await token.approve(meta.routerAddress,item.amountIn);item.status="授权中";item.hashOrError=`approve: ${ap.hash}`;renderTradePlan();const approvalReceipt=await ap.wait();if(approvalReceipt.status!==1)throw new Error("Token 授权失败");if(state.tradeStopped){item.status="已停止";item.hashOrError="授权完成，卖出未提交";renderTradePlan();return}}const deadline=Math.floor(Date.now()/1000)+deadlineMin*60;tx=await router.swapExactTokensForETHSupportingFeeOnTransferTokens(item.amountIn,item.amountOutMin,[meta.tokenAddress,meta.weth],wallet.address,deadline)}item.status="已提交";item.hashOrError=tx.hash;pending.push({item,tx});renderTradePlan()}catch(e){item.status="失败";item.hashOrError=e?.shortMessage||e?.message||String(e);renderTradePlan()}if(delay&&!state.tradeStopped)await sleep(delay)});await Promise.all(pending.map(async({item,tx})=>{try{const receipt=await tx.wait();item.status=receipt.status===1?"成功":"失败"}catch(e){item.status="失败";item.hashOrError=e?.shortMessage||e?.message||String(e)}renderTradePlan()}));$("stopTradeBtn").disabled=true;setMetric(els.tradeStatusMetric,state.tradeStopped?"已停止":"执行完成")}
function getCollectProvider(){ensureEthers();const rpc=els.collectRpcUrl.value.trim();if(!rpc)throw new Error("请输入一键归集 RPC URL");return new ethers.JsonRpcProvider(rpc)}
function getCollectAssetType(){return els.collectNativeAsset.checked?"native":"token"}
function resetCollectPlan(status){state.collectPlan=[];renderCollectPlan();$("executeCollectBtn").disabled=true;if(status)setMetric(els.collectStatusMetric,status)}
function refreshCollectAssetType(){const native=getCollectAssetType()==="native";els.collectTokenAddress.disabled=native;$("loadCollectTokenBtn").textContent=native?"读取主币信息":"读取 Token 信息";els.collectTokenInfo.innerHTML=native?`<div class="muted">主币通过当前 RPC 读取，不需要合约地址。归集数量会自动扣除预估 gas。</div>`:`<div class="muted">读取后显示 Token 名称、符号和精度。</div>`;els.collectRuleText.textContent=native?"每个私钥钱包自动读取主币余额，扣除预估 gas 后全部转到归集地址。":"每个私钥钱包自动读取 Token 余额，并把全部余额转到归集地址。";els.collectRuleWarning.innerHTML=native?"<strong>注意：</strong>预览金额按当前 gas 价格估算；执行前会重新计算，以尽量归集全部可用主币。":"<strong>注意：</strong>每个归集钱包必须有足够原生币支付 gas。Token 如果带转账税，实际到账可能小于预览余额。";els.collectSafetyWarning.innerHTML=native?"<strong>安全提醒：</strong>归集会真实转出每个私钥钱包中扣除手续费后的主币，请先小额测试。":"<strong>安全提醒：</strong>归集会真实转出每个私钥钱包中的该 Token，请先小额测试。";state.collectProvider=null;state.collectTokenMeta=null;setMetric(els.collectTokenMetric,native?"主币":"未读取");resetCollectPlan("资产类型已变更")}
async function loadCollectTokenInfo(){ensureEthers();const provider=getCollectProvider(),addr=els.collectTokenAddress.value.trim();if(!ethers.isAddress(addr))throw new Error("归集 Token 合约地址不正确");const token=new ethers.Contract(addr,ERC20_ABI,provider);const [name,symbol,decimals]=await Promise.all([token.name().catch(()=>""),token.symbol().catch(()=>""),token.decimals()]);state.collectProvider=provider;state.collectTokenMeta={type:"token",tokenAddress:ethers.getAddress(addr),name,symbol,decimals:Number(decimals)};setMetric(els.collectTokenMetric,symbol||shortAddress(addr));setMetric(els.collectStatusMetric,"Token 已读取");els.collectTokenInfo.innerHTML=`<div><strong>Token：</strong>${name||"-"} ${symbol?`(${symbol})`:""}</div><div><strong>精度：</strong>${decimals}</div><div><strong>合约：</strong>${ethers.getAddress(addr)}</div>`}
async function loadCollectNativeInfo(){ensureEthers();const provider=getCollectProvider(),network=await provider.getNetwork(),feeData=await provider.getFeeData(),symbol=getNativeSymbol(network.chainId),gasPrice=feeData.gasPrice||feeData.maxFeePerGas;state.collectProvider=provider;state.collectTokenMeta={type:"native",tokenAddress:null,name:"原生币",symbol,decimals:18,chainId:network.chainId};setMetric(els.collectTokenMetric,symbol);setMetric(els.collectStatusMetric,"原生币已读取");els.collectTokenInfo.innerHTML=`<div><strong>资产：</strong>原生币 (${symbol})</div><div><strong>Chain ID：</strong>${network.chainId}</div><div><strong>当前 gas 价格：</strong>${gasPrice?`${ethers.formatUnits(gasPrice,"gwei")} Gwei`:"RPC 未返回"}</div>`}
async function loadCollectAssetInfo(){return getCollectAssetType()==="native"?loadCollectNativeInfo():loadCollectTokenInfo()}
async function getCollectNativeQuote(provider,from,to,balanceWei){const feeData=await provider.getFeeData(),gasPrice=feeData.gasPrice||feeData.maxFeePerGas;if(!gasPrice)throw new Error("RPC 未返回可用 gas 价格");let gasLimit=await provider.estimateGas({from,to,value:balanceWei>1n?1n:0n,gasPrice});for(let i=0;i<2;i++){const feeWei=gasLimit*gasPrice;if(balanceWei<=feeWei)return{amountWei:0n,feeWei,gasLimit,gasPrice};const nextGasLimit=await provider.estimateGas({from,to,value:balanceWei-feeWei,gasPrice});if(nextGasLimit===gasLimit)break;gasLimit=nextGasLimit}const feeWei=gasLimit*gasPrice;return{amountWei:balanceWei>feeWei?balanceWei-feeWei:0n,feeWei,gasLimit,gasPrice}}
function parseCollectPrivateKeys(){ensureEthers();const lines=els.collectPrivateKeys.value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)throw new Error("请输入至少一个待归集钱包私钥");const seen=new Set(),ws=[];for(const line of lines){const pk=normalizePrivateKey(line.split(/[,\s]+/)[0]);const w=new ethers.Wallet(pk);if(!seen.has(w.address.toLowerCase())){seen.add(w.address.toLowerCase());ws.push({index:ws.length+1,privateKey:pk,address:w.address})}}return ws}
function getCollectConcurrency(){const value=Number(els.collectConcurrency.value);if(!Number.isInteger(value)||value<1||value>20)throw new Error("归集并发钱包数必须是 1 到 20 之间的整数");return value}
async function buildCollectPlan(){ensureEthers();const assetType=getCollectAssetType();if(!state.collectTokenMeta||state.collectTokenMeta.type!==assetType)await loadCollectAssetInfo();const to=els.collectToAddress.value.trim();if(!ethers.isAddress(to))throw new Error("归集接收地址不正确");const toAddress=ethers.getAddress(to),wallets=parseCollectPrivateKeys(),provider=state.collectProvider,meta={...state.collectTokenMeta,toAddress},token=meta.type==="token"?new ethers.Contract(meta.tokenAddress,ERC20_ABI,provider):null,concurrency=getCollectConcurrency();const plan=await mapWithConcurrency(wallets,concurrency,async(w,i)=>{const nativeWei=await provider.getBalance(w.address);let amountWei=0n,feeWei=0n,gasLimit=0n,gasPrice=0n,status="待执行",hashOrError="";if(w.address.toLowerCase()===toAddress.toLowerCase()){status="跳过";hashOrError="归集接收地址本身，跳过"}else if(meta.type==="native"){try{const quote=await getCollectNativeQuote(provider,w.address,toAddress,nativeWei);({amountWei,feeWei,gasLimit,gasPrice}=quote);if(amountWei<=0n){status="跳过";hashOrError=nativeWei<=0n?"原生币余额为 0":"余额不足支付预估 gas"}}catch(e){status="失败";hashOrError=e?.shortMessage||e?.message||String(e)}}else{amountWei=await token.balanceOf(w.address);if(amountWei<=0n){status="跳过";hashOrError="Token 余额为 0"}}return{index:i+1,...w,toAddress,amountWei,amountText:ethers.formatUnits(amountWei,meta.decimals),nativeWei,nativeText:ethers.formatEther(nativeWei),feeWei,gasLimit,gasPrice,status,hashOrError}});state.collectTokenMeta=meta;state.collectPlan=plan;const ready=plan.filter(x=>x.status==="待执行"&&x.amountWei>0n).length;setMetric(els.collectWalletCountMetric,String(plan.length));setMetric(els.collectReadyCountMetric,String(ready));setMetric(els.collectStatusMetric,"预览已生成");renderCollectPlan();$("executeCollectBtn").disabled=ready===0}
function renderCollectPlan(){if(!state.collectPlan.length){els.collectPlanBody.innerHTML=`<tr><td colspan="6" class="empty">请先生成归集预览</td></tr>`;els.collectSummaryText.textContent="暂无归集计划";setMetric(els.collectWalletCountMetric,"0");setMetric(els.collectReadyCountMetric,"0");return}const meta=state.collectTokenMeta,collectableItems=state.collectPlan.filter(x=>x.status!=="跳过"&&x.amountWei>0n),total=collectableItems.reduce((s,x)=>s+x.amountWei,0n),ready=collectableItems.length,unit=meta.symbol||(meta.type==="native"?"原生币":"Token");els.collectSummaryText.textContent=`共 ${state.collectPlan.length} 个钱包，可归集 ${ready} 个，合计 ${ethers.formatUnits(total,meta.decimals)} ${unit}`;els.collectPlanBody.innerHTML=state.collectPlan.map(x=>`<tr><td>${x.index}</td><td class="hash">${x.address}</td><td>${x.amountText} ${unit}${meta.type==="native"&&x.feeWei>0n?`<div class="muted">预估 gas：${ethers.formatEther(x.feeWei)} ${unit}</div>`:""}</td><td>${x.nativeText} ${meta.type==="native"?unit:"原生币"}</td><td>${renderStatus(x.status)}</td><td class="hash">${x.hashOrError||"-"}</td></tr>`).join("")}
async function executeCollectPlan(){ensureEthers();if(!state.collectPlan.length)throw new Error("请先生成归集预览");const items=state.collectPlan.filter(x=>x.status==="待执行"&&x.amountWei>0n),concurrency=getCollectConcurrency();if(!items.length)throw new Error("没有可执行的归集钱包");const meta=state.collectTokenMeta,assetLabel=meta.type==="native"?meta.symbol:"Token";if(!confirm(`确认以最多 ${concurrency} 个钱包并发，将 ${items.length} 个钱包的${assetLabel}全部归集到 ${meta.toAddress}？`))return;state.collectStopped=false;$("executeCollectBtn").disabled=true;$("stopCollectBtn").disabled=false;setMetric(els.collectStatusMetric,`并发执行中 (${concurrency})`);const provider=state.collectProvider,delay=Math.round(Math.max(0,Number(els.collectDelaySeconds.value||0))*1000),pending=[];await mapWithConcurrency(items,concurrency,async item=>{if(state.collectStopped){item.status="已停止";item.hashOrError="用户停止执行";renderCollectPlan();return}item.status="执行中";item.hashOrError="";renderCollectPlan();try{const wallet=new ethers.Wallet(item.privateKey,provider);let tx;if(meta.type==="native"){const balanceWei=await provider.getBalance(wallet.address),quote=await getCollectNativeQuote(provider,wallet.address,meta.toAddress,balanceWei);if(quote.amountWei<=0n)throw new Error("当前余额不足支付 gas");Object.assign(item,quote,{amountText:ethers.formatEther(quote.amountWei),nativeWei:balanceWei,nativeText:ethers.formatEther(balanceWei)});renderCollectPlan();tx=await wallet.sendTransaction({to:meta.toAddress,value:quote.amountWei,gasLimit:quote.gasLimit,gasPrice:quote.gasPrice})}else{const token=new ethers.Contract(meta.tokenAddress,ERC20_ABI,wallet);tx=await token.transfer(meta.toAddress,item.amountWei)}item.status="已提交";item.hashOrError=tx.hash;pending.push({item,tx});renderCollectPlan()}catch(e){item.status="失败";item.hashOrError=e?.shortMessage||e?.message||String(e);renderCollectPlan()}if(delay&&!state.collectStopped)await sleep(delay)});await Promise.all(pending.map(async({item,tx})=>{try{const receipt=await tx.wait();item.status=receipt.status===1?"成功":"失败"}catch(e){item.status="失败";item.hashOrError=e?.shortMessage||e?.message||String(e)}renderCollectPlan()}));$("stopCollectBtn").disabled=true;setMetric(els.collectStatusMetric,state.collectStopped?"已停止":"执行完成")}
document.querySelectorAll(".menu-item").forEach(i=>i.addEventListener("click",()=>switchPage(i.dataset.page)));
els.transferNativeAsset.addEventListener("change",refreshTransferAssetType);
document.querySelectorAll('input[name="transferMode"]').forEach(i=>i.addEventListener("change",refreshTransferMode));
document.querySelectorAll('input[name="tradeMode"]').forEach(i=>i.addEventListener("change",refreshTradeMode));
els.collectNativeAsset.addEventListener("change",refreshCollectAssetType);
[els.rpcUrl,els.privateKey,els.tokenAddress,els.minAmount,els.maxAmount,els.fixedAmount,els.randomDecimals,els.recipients].forEach(i=>i.addEventListener("input",()=>resetTransferPlan("配置已变更")));
$("validateWalletBtn").onclick=()=>initWallet().catch(toastError);
$("loadTokenBtn").onclick=()=>loadTransferAsset().catch(toastError);
$("previewBtn").onclick=()=>buildPlan().catch(toastError);
$("executeBtn").onclick=()=>executePlan().catch(toastError);
$("stopBtn").onclick=()=>{state.stopped=true;$("stopBtn").disabled=true;setMetric(els.metricStatus,"停止中")};
$("clearPrivateKeyBtn").onclick=()=>{els.privateKey.value="";state.provider=null;state.wallet=null;state.rpcUrl=null;state.chainId=null;state.token=null;state.tokenMeta=null;state.plan=[];renderPlan();$("executeBtn").disabled=true;setMetric(els.metricWallet,"未验证");setMetric(els.metricStatus,"私钥已清空");els.networkStatus.textContent="未连接";els.walletInfo.innerHTML=`<div class="muted">私钥已清空。</div>`};
$("togglePkBtn").onclick=()=>{const p=els.privateKey.type==="password";els.privateKey.type=p?"text":"password";$("togglePkBtn").textContent=p?"隐藏":"显示"};
$("generateWalletBtn").onclick=()=>{try{generateWallets()}catch(e){toastError(e)}};
$("copyWalletAddressBtn").onclick=()=>copyText(state.generatedWallets.map(x=>x.address).join("\n")).then(()=>alert("地址列表已复制"));
$("copyWalletFullBtn").onclick=()=>copyText("序号,钱包地址,私钥\n"+state.generatedWallets.map(x=>`${x.index},${x.address},${x.privateKey}`).join("\n")).then(()=>alert("完整钱包信息已复制"));
$("clearWalletGeneratedBtn").onclick=()=>{if(confirm("确认清空当前页面生成的钱包信息？")){state.generatedWallets=[];renderGeneratedWallets()}};
$("loadTradeTokenBtn").onclick=()=>loadTradeTokenInfo().catch(toastError);
$("previewTradeBtn").onclick=()=>buildTradePlan().catch(toastError);
$("executeTradeBtn").onclick=()=>executeTradePlan().catch(toastError);
$("stopTradeBtn").onclick=()=>{state.tradeStopped=true;$("stopTradeBtn").disabled=true;setMetric(els.tradeStatusMetric,"停止中")};
$("loadCollectTokenBtn").onclick=()=>loadCollectAssetInfo().catch(toastError);
$("previewCollectBtn").onclick=()=>buildCollectPlan().catch(toastError);
$("executeCollectBtn").onclick=()=>executeCollectPlan().catch(toastError);
$("stopCollectBtn").onclick=()=>{state.collectStopped=true;$("stopCollectBtn").disabled=true;setMetric(els.collectStatusMetric,"停止中")};
els.tradeSellAllPercent.onchange=()=>{refreshSellAllMode();state.tradePlan=[];renderTradePlan();$("executeTradeBtn").disabled=true};
[els.collectRpcUrl,els.collectTokenAddress].forEach(i=>i.addEventListener("input",()=>{state.collectProvider=null;state.collectTokenMeta=null;resetCollectPlan("配置已变更")}));
[els.collectToAddress,els.collectPrivateKeys].forEach(i=>i.addEventListener("input",()=>resetCollectPlan("配置已变更")));
refreshTransferAssetType();refreshTransferMode();refreshTradeMode();refreshCollectAssetType();setMetric(els.collectStatusMetric,"待配置");renderGeneratedWallets();switchPage("transfer");
